input = ["r", "p", "s"]
computer_response = rand(3)

puts "Let's play! Choose rock (r), paper (p), or scissors (s)."
input = gets.chomp

if computer_response == 0 && input == "r"
  puts "Computer chose rock."
  puts "Player chose rock."
  puts "Tie!"
elsif computer_response == 0 && input == "p"
  puts "Computer chose rock."
  puts "Player chose paper."
  puts "Player wins!"
elsif computer_response == 0 && input == "s"
  puts "Computer chose rock."
  puts "Player chose scissors."
  puts "Computer wins!"
elsif computer_response == 1 && input == "r"
  puts "Computer chose paper."
  puts "Player chose rock."
  puts "Computer wins!"
elsif computer_response == 1 && input == "p"
  puts "Computer chose paper."
  puts "Player chose paper."
  puts "Tie!"
elsif computer_response == 1 && input == "s"
  puts "Computer chose paper."
  puts "Player chose scissors."
  puts "Player wins!"
elsif computer_response == 2 && input == "r"
  puts "Computer chose scissors."
  puts "Player chose rock."
  puts "Player wins!"
elsif computer_response == 2 && input == "p"
  puts "Computer chose scissors."
  puts "Player chose paper."
  puts "Computer wins!"
elsif computer_response == 2 && input == "s"
  puts "Computer chose scissors."
  puts "Player chose scissors."
  puts "Tie!"
else
  puts "Invalid entry. Please try again."
end
